### ISSUE TITLE
Support all join types in spark

### ISSUE THREAD

**Issue by explicite** [VirtusLab/iskra#3]
Here we can find definition types in spark join https://github.com/apache/spark/blob/05c0fa573881b49d8ead9a5e16071190e5841e1b/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/joinTypes.scala

Should be done under. 
https://github.com/VirtusLab/typed-frames/blob/a407cbc1ad704ead7b44293c285c87a3e58faedf/src/main/Join.scala#L10

**Comment by prolativ** [comment]
Fixed by https://github.com/VirtusLab/iskra/pull/19
